server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  view:
    prefix: /
    suffix: .jsp    
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          